KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-password"
    user_admin="admin-password"
    user_writer-app="writer-password"
    user_consumer-app="consumer-password";
};

